lib/webapp_web/router.ex
defmodule WebappWeb.Router do
  use WebappWeb, :router

  import WebappWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
    plug WebappWeb.TeamContext
  end

  pipeline :new_layout do
    plug :put_root_layout, html: {WebappWeb.Layouts, :root}
  end

  pipeline :authenticated do
    plug :require_authenticated_user
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug WebappWeb.HypervisorTokenAuth
  end

  scope "/api/v1", WebappWeb.ApiV1 do
    pipe_through :api

    resources "/distributions", DistributionController, except: [:new, :edit]
  end

  scope "/", WebappWeb do
    pipe_through :browser
    get "/", PageController, :index
    get "/health", PageController, :health
  end

  scope "/", WebappWeb do
    pipe_through [:browser, :authenticated, :redirect_if_user_must_update_password]

    # Machine
    resources "/machines", MachineController, except: [:new, :create]
    get "/machines/:id/console", MachineController, :console
    post "/machines/:id/start", MachineController, :start
    post "/machines/:id/stop", MachineController, :stop
    post "/machines/:id/restart", MachineController, :restart
    post "/machines/:id/poweroff", MachineController, :poweroff
    get "/hypervisors/:hypervisor_id/machines/new", MachineController, :new
    post "/hypervisors/:hypervisor_id/machines/create", MachineController, :create
  end

  scope "/admin", WebappWeb.Admin, as: :admin do
    pipe_through [:browser, :authenticated, :redirect_if_user_must_update_password]

    resources "/hypervisors", HypervisorController do
      resources "/networks", NetworkController, only: [:new, :create, :index]
    end
    get "/hypervisors/:id/machines", HypervisorController, :index_machines

    resources "/regions", RegionController
    resources "/machines", MachineController, only: [:index]
    resources "/plans", PlanController
    resources "/networks", NetworkController, except: [:new, :create, :index]
    resources "/ip_pools", IpPoolController, except: [:edit, :update, :delete]
    resources "/users", UserController, except: [:edit, :update, :delete]
    resources "/teams", TeamController, only: [:index]
    resources "/jobs", JobController, only: [:index]
  end

  # Enable LiveDashboard and Swoosh mailbox preview in development
  if Application.compile_env(:webapp, :dev_routes) do
    import Phoenix.LiveDashboard.Router

    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
      live_dashboard "/dashboard", metrics: WebappWeb.Telemetry
    end
  end

  # Other scopes may use custom stacks.
  # scope "/api", WebappWeb do
  #   pipe_through :api
  # end

  ## Authentication routes

  scope "/", WebappWeb do
    pipe_through [:browser, :new_layout, :redirect_if_user_is_authenticated]

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", WebappWeb do
    pipe_through [:browser, :new_layout, :authenticated, :redirect_if_user_must_update_password]
    get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email
    resources "/users/teams", TeamController, except: [:delete] do
      get "/members/new", TeamMembersController, :invite_member
      post "/members", TeamMembersController, :send_invite
      delete "/members/:id", TeamMembersController, :delete_member
      get "/members/:id/edit", TeamMembersController, :edit_member
      put "/members/:id", TeamMembersController, :update_member
    end
    resources "/users/keys", SSHPublicKeyController, except: [:edit]
  end

  scope "/", WebappWeb do
    pipe_through [:browser, :new_layout, :authenticated]

    get "/users/settings", UserSettingsController, :edit
    put "/users/settings", UserSettingsController, :update
  end

  scope "/", WebappWeb do
    pipe_through [:browser, :new_layout]

    delete "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :edit
    post "/users/confirm/:token", UserConfirmationController, :update
    get "/users/join/:token", UserInvitationController, :edit
    put "/users/join/:token", UserInvitationController, :update
  end
end

lib/webapp_web/controllers/admin/machine_controller.ex
defmodule WebappWeb.Admin.MachineController do
  use WebappWeb, :controller

  alias Webapp.{
    Machines,
    Hypervisors,
    Hypervisors.Hypervisor,
    Regions
  }

  plug :load_resource,
    model: Hypervisor,
    id_name: "hypervisor_id",
    only: [:index],
    preload: [:hypervisor_type, machines: Hypervisors.preload_active_machines]

  def index(conn, _params) do
    machines = Machines.list_machines([:plan, :networks, :distribution, hypervisor: :region])
    regions = Regions.list_usable_regions()
    render(conn, "index.html", machines: machines, hypervisor: nil, regions: regions)
  end
end

lib/webapp_web/controllers/machine_controller.ex
defmodule WebappWeb.MachineController do
  use WebappWeb, :controller

  alias Webapp.{
    Machines,
    Machines.Machine,
    Hypervisors,
    Hypervisors.Hypervisor,
    Networks,
    Plans,
    Regions,
    Teams,
    Teams.Team,
    Distributions,
    Notifications.Notifications
  }

  plug :load_and_authorize_resource,
    current_user: :current_member,
    model: Machine,
    non_id_actions: [:index, :create, :new],
    preload: [:plan, :networks, :distribution, :job, ipv4: [:ip_pool], hypervisor: :region]

  plug :load_resource,
    model: Hypervisor,
    id_name: "hypervisor_id",
    only: [:new, :create],
    preload: [:region, :hypervisor_type, machines: [:networks, :plan, :distribution]],
    required: true

  plug :load_references when action in [:new, :create, :edit, :update]

  plug :ensure_user_has_ssh_private_key when action in [:new]

  def index(%Conn{assigns: %{current_team: %Team{} = team}} = conn, _params) do
    machines =
      Machines.list_team_machines(team, [:plan, :networks, :distribution, hypervisor: :region])

    hypervisors = Hypervisors.list_hypervisors()
    regions = Regions.list_usable_regions()

    render(conn, "index.html",
      machines: machines,
      hypervisor: false,
      hypervisors: hypervisors,
      regions: regions
    )
  end

  def new(conn, _params) do
    changeset = Machines.change_machine(%Machine{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"machine" => machine_params}) do
    Notifications.publish(
      :info,
      "#{conn.assigns.current_user.email} requested to create new VM: #{machine_params["name"]}"
    )

    case Machines.create_machine(machine_params) do
      {:ok, %{machine: machine}} ->
        team = Teams.get_team!(machine.team_id)
        conn
        |> redirect(to: team_path(team, ~p"/machines/#{machine}"))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)

      {:error, :machine, %Ecto.Changeset{} = changeset, _} ->
        render(conn, "new.html", changeset: changeset)

      {:error, :hypervisor_not_found, %Ecto.Changeset{} = changeset} ->
        conn
        |> put_flash(:error, "Couldn't spawn new machine.")
        |> render("new.html", changeset: changeset)

      {:error, _task, maybe_error, _} ->
        changeset =
          %Machine{}
          |> Machine.changeset(machine_params)

        error = if is_binary(maybe_error) do
           maybe_error
        else
          "Couldn't spawn new machine."
        end

        conn
        |> put_flash(:error, error)
        |> render("new.html", changeset: changeset)
    end
  end

  def show(conn, _params) do
    machine = conn.assigns[:machine]

    case Machines.update_status(machine) do
      {:ok, %Machine{} = machine} ->
        conn
        |> render("show.html", machine: machine)

      {:error, message} ->
        conn
        |> put_flash(:error, message)
        |> redirect(to: team_path(:machine_path, conn, :show, machine))
    end
  end

  def edit(conn, _params) do
    machine = conn.assigns[:machine]
    changeset = Machines.change_machine(machine)

    render(conn, "settings.html", machine: machine, changeset: changeset)
  end

  # Add network
  def update(conn, %{"machine" => %{"network_ids" => network_id}}) do
    machine = conn.assigns[:machine]
    network = Networks.get_network!(network_id)

    case Machines.add_network_to_machine(machine, network) do
      {:ok, %{machine: machine}} ->
        conn
        |> put_flash(:info, "Machine #{machine.name} is now connected to network #{network.name}")
        |> redirect(to: team_path(:machine_path, conn, :show, machine))

      # Errors from changeset should be displayed!
      {:error, %Ecto.Changeset{} = _changeset} ->
        conn
        |> put_flash(
          :error,
          "Couldn't connect machine #{machine.name} to network #{network.name}"
        )
        |> redirect(to: team_path(:machine_path, conn, :show, machine))

      # Errors from changeset should be displayed!
      {:error, :machine, %Ecto.Changeset{} = _changeset, _} ->
        conn
        |> put_flash(
          :error,
          "Couldn't connect machine #{machine.name} to network #{network.name}"
        )
        |> redirect(to: team_path(:machine_path, conn, :show, machine))

      {:error, :hypervisor, error, _} ->
        conn
        |> put_flash(:error, error)
        |> redirect(to: team_path(:machine_path, conn, :show, machine))

      {:error, :hypervisor_not_found} ->
        conn
        |> put_flash(:error, "Couldn't create virtual machine")
        |> redirect(to: team_path(:machine_path, conn, :show, machine))
    end
  end

  # Change machine name
  def update(conn, %{"id" => id, "machine" => %{"name" => _name} = _machine_params}) do
    machine = Machines.get_machine!(id, [:networks])

    conn
    |> put_flash(:error, "Not implemented yet.")
    |> redirect(to: team_path(:machine_path, conn, :show, machine))
  end

  def delete(conn, _params) do
    machine = conn.assigns[:machine]

    Notifications.publish(
      :info,
      "#{conn.assigns.current_user.email} requested removal of VM #{machine.name} (ID: #{machine.id})"
    )

    case Machines.delete_machine(machine) do
      {:ok, _machine} ->
        conn
        |> put_flash(:info, "Machine #{machine.name} has been marked for deletion")
        |> redirect(to: team_path(:machine_path, conn, :index))

      {:error, :hypervisor, error, _changes} ->
        conn
        |> put_flash(:error, error)
        |> redirect(to: team_path(:machine_path, conn, :index))

      {:error, :hypervisor_not_found} ->
        conn
        |> put_flash(:error, "Couldn't delete machine #{machine.name}")
        |> redirect(to: team_path(:machine_path, conn, :index))
    end
  end

  def start(conn, _params) do
    machine = conn.assigns[:machine]

    Notifications.publish(
      :info,
      "#{conn.assigns.current_user.email} requested start of VM #{machine.name} (ID: #{machine.id})"
    )

    case Machines.start_machine(machine) do
      {:ok, _} ->
        conn
        |> put_flash(:info, "Machine #{machine.name} is being started")
        |> redirect(to: team_path(:machine_path, conn, :show, machine))

      {:error, error} ->
        conn
        |> put_flash(:error, error)
        |> redirect(to: team_path(:machine_path, conn, :show, machine))
    end
  end

  def stop(conn, _params) do
    machine = conn.assigns[:machine]

    Notifications.publish(
      :info,
      "#{conn.assigns.current_user.email} requested stop of VM #{machine.name} (ID: #{machine.id})"
    )

    case Machines.stop_machine(machine) do
      {:ok, _} ->
        conn
        |> put_flash(:info, "Machine #{machine.name} is being stopped")
        |> redirect(to: team_path(:machine_path, conn, :show, machine))

      {:error, error} ->
        conn
        |> put_flash(:error, error)
        |> redirect(to: team_path(:machine_path, conn, :show, machine))
    end
  end

  def restart(conn, _params) do
    machine = conn.assigns[:machine]

    Notifications.publish(
      :info,
      "#{conn.assigns.current_user.email} requested to restart VM #{machine.name} (ID: #{machine.id})"
    )

    case Machines.restart_machine(machine) do
      {:ok, _} ->
        conn
        |> put_flash(:info, "Machine #{machine.name} is being restarted")
        |> redirect(to: team_path(:machine_path, conn, :show, machine))

      {:error, error} ->
        conn
        |> put_flash(:error, error)
        |> redirect(to: team_path(:machine_path, conn, :show, machine))
    end
  end

  def poweroff(conn, _params) do
    machine = conn.assigns[:machine]

    Notifications.publish(
      :info,
      "#{conn.assigns.current_user.email} requested to poweroff VM #{machine.name} (ID: #{machine.id})"
    )

    case Machines.poweroff_machine(machine) do
      {:ok, _} ->
        conn
        |> put_flash(:info, "Machine #{machine.name} is being powered off")
        |> redirect(to: team_path(:machine_path, conn, :show, machine))

      {:error, error} ->
        conn
        |> put_flash(:error, error)
        |> redirect(to: team_path(:machine_path, conn, :show, machine))
    end
  end

  def console(conn, _params) do
    machine = conn.assigns[:machine]

    Notifications.publish(
      :info,
      "#{conn.assigns.current_user.email} requested access to serial console of VM #{machine.name} (ID: #{machine.id})"
    )

    case Machines.console_machine(machine) do
      {:ok, console} ->
        token = Base.encode64(console["user"] <> ":" <> console["password"])
        render(conn, "console.html", machine: machine, console: console, token: token)

      {:error, error} ->
        conn
        |> put_flash(:error, error)
        |> redirect(to: team_path(:machine_path, conn, :show, machine))
    end
  end

  defp load_references(conn, _) do
    # The :index, :create and :new are under /hypervisors resource
    # for them, we use load_hypervisor which puts assign with hypervisor.
    # For other methods we're loading hypervisor from machine.
    hypervisor =
      case Map.has_key?(conn.assigns, :hypervisor) do
        true -> conn.assigns[:hypervisor]
        _ -> conn.assigns[:machine].hypervisor
      end

    conn
    |> assign(:networks, Hypervisors.list_hypervisor_networks(hypervisor))
    |> assign(:plans, Plans.list_plans())
    |> assign(:teams, Teams.list_teams())
    |> assign(:distributions, Distributions.list_active_distributions())
  end

  defp ensure_user_has_ssh_private_key(conn, _) do
    case conn.assigns.current_user.ssh_public_keys do
      [] ->
        conn
        |> put_flash(:error, "You need to add your SSH public key before creating a machine. Without it, you won't be able to access your machine.")
        |> redirect(to: ~p"/users/keys")
        |> halt()

      _ ->
        conn
    end
  end
end

lib/webapp_web/views/admin/machine_view.ex
defmodule WebappWeb.Admin.MachineView do
  use WebappWeb, :view
  import WebappWeb.MachineView, only: [map_status_to_css: 1, status_icon: 1]

  def extract_ids(machines) do
    Enum.map_join(machines, ",", fn machine ->
      machine.id
    end)
  end
end

lib/webapp_web/views/machine_view.ex
defmodule WebappWeb.MachineView do
  use WebappWeb, :view

  import Webapp.Machines, only: [machine_can_do?: 2]
  import Webapp.Hypervisors, only: [get_hypervisor_url: 3]

  def hypervisors_select_options(hypervisors) do
    for hypervisor <- hypervisors do
      {hypervisor.name, hypervisor.id}
    end
  end

  def networks_select_options(networks) do
    for network <- networks do
      label = "#{network.name} (#{network.network})"
      {label, network.id}
    end
  end

  def plans_select_options(plans) do
    for plan <- plans do
      details = [
        Integer.to_string(plan.storage),
        Integer.to_string(plan.ram),
        Integer.to_string(plan.cpu)
      ]

      label = plan.name <> " (" <> Enum.join(details, "/") <> ")"
      {label, plan.id}
    end
  end

  def team_select_options(teams) do
    for team <- teams do
      {team.name, team.id}
    end
  end

  def ssh_public_keys_select_options(public_keys) do
    for public_key <- public_keys do
      {public_key.title, public_key.id}
    end
  end

  def map_status_to_css(status) do
    case status do
      "Creating" -> "is-light"
      "Stopped" -> "is-dark"
      "Running" -> "is-success"
      "Bootloader" -> "is-success"
      "Failed" -> "is-danger"
      _ -> "is-white"
    end
  end

  def status_icon(status) do
    case status do
      "Creating" -> "fas fa-spinner fa-spin"
      "Stopped" -> "fas fa-square"
      "Running" -> "fas fa-play"
      "Bootloader" -> "fas fa-play"
      "Failed" -> "fas fa-exclamation-circle"
      _ -> ""
    end
  end
end

lib/webapp_web/templates/machine/_menu.html.eex
<div class="level" data-machine-id="<%= @machine.id %>">
  <div class="level-left">
     <div class="level-item">
       <h1><%= @machine.name %></h1>
     </div>

     <div class="level-item">
       <div class="tags has-addons">
         <span class="tag status status-icon <%= map_status_to_css(@machine.last_status) %>" data-status="<%= map_status_to_css(@machine.last_status) %>"><i class="<%= status_icon(@machine.last_status) %>"></i></span>
         <span class="tag status <%= map_status_to_css(@machine.last_status) %>" data-status="<%= map_status_to_css(@machine.last_status) %>"><%= @machine.last_status %></span>
       </div>
     </div>
  </div>

  <div class="level-right">
    <div class="level-item <%= action_css_class(@machine, :start) %>">
      <%= link "Start",
        to: team_path(:machine_path, @conn, :start, @machine),
        method: :post,
        class: "button is-rounded is-success" %>
    </div>

    <div class="level-item <%= action_css_class(@machine, :restart) %>">
       <%= link "Restart",
         to: team_path(:machine_path, @conn, :restart, @machine),
         method: :post,
         data: [confirm: "Do you really want to restart the #{@machine.name} machine?"],
         class: "button is-rounded is-info" %>
    </div>

    <div class="level-item <%= action_css_class(@machine, :stop) %>">
      <%= link "Stop",
         to: team_path(:machine_path, @conn, :stop, @machine),
         method: :post, data: [confirm: "Do you really want to restart the #{@machine.name} machine?"],
         class: "button is-rounded is-danger" %>
    </div>

    <div class="level-item <%= action_css_class(@machine, :poweroff) %>">
       <%= link "Poweroff",
        to: team_path(:machine_path, @conn, :poweroff, @machine),
        method: :post,
        data: [confirm: "Do you really want to poweroff the #{@machine.name} machine?"],
        class: "button is-rounded is-dark" %>
    </div>
  </div>
</div>

<div class="tabs">
  <ul>
    <%= active_link(@conn, "Dashboard", to: team_path(:machine_path, @conn, :show, @machine), active: :exact)  %>
    <%= active_link(@conn, "Console", to: team_path(:machine_path, @conn, :console, @machine), active: :exact, class: action_css_class(@machine, :console))  %>
    <%= active_link(@conn, "Settings", to: team_path(:machine_path, @conn, :edit, @machine), active: :exact)  %>
  </ul>
</div>

<script type="text/javascript">
var machine = {
  id: <%= @machine.id %>,
}
</script>
<script type="text/javascript" src="<%= Routes.static_path(@conn, "/assets/machine.js") %>"></script>

lib/webapp_web/templates/machine/_new_button.html.eex
<%= if @hypervisor do %>
  <span><%= link "New Machine", to: team_path(:machine_path, @conn, :new, @region), class: "button is-rounded is-primary" %></span>
<% else %>
  <%= if not Enum.empty?(@regions) do %>
  <div class="dropdown is-hoverable is-right">
    <div class="dropdown-trigger">
      <button class="button is-rounded is-primary" aria-haspopup="true" aria-controls="dropdown-menu">
        <span>New machine</span>
        <span class="icon is-small">
                <i class="fas fa-angle-down" aria-hidden="true"></i>
              </span>
      </button>
    </div>
    <div class="dropdown-menu" id="dropdown-menu" role="menu">
      <div class="dropdown-content">
        <%= for region <- @regions do %>
          <% hypervisor = Webapp.Regions.list_region_hypervisors(region) |> Enum.random %>
          <%= link "#{region.name}", to: team_path(:machine_path, @conn, :new, hypervisor), class: "dropdown-item" %>
        <% end %>
      </div>
    </div>
  </div>
  <% end %>
<% end %>

lib/webapp_web/templates/machine/console.html.eex
<nav class="breadcrumb" aria-label="breadcrumbs">
  <ul>
    <li><%= link "Home", to: Routes.page_path(@conn, :index) %></li>
    <li><%= link "My Machines", to: team_path(:machine_path, @conn, :index) %></li>
    <li><%= link @machine.name, to: team_path(:machine_path, @conn, :show, @machine)  %></li>
    <li class="is-active"><a>Console</a></li>
  </ul>
</nav>



<%= render "_menu.html", assigns %>

<div id="console-wrapper" class="box is-relative">
  <button alt="Toggle fullscreen" id="console-toggle" class="button"><i class="fas fa-compress"></i></button>
  <iframe id="console" type="text/html" src="<%= get_hypervisor_url(@machine.hypervisor, :gotty, @console["port"]) %>/<%= @token %>/tty/"></iframe>
</div>

<script>
document.getElementById("console-toggle").addEventListener('touchstart', toggleConsoleFullscreen);
document.getElementById("console-toggle").addEventListener("keypress", function(e) {
  if (e.keyCode === 13 || e.keyCode == 0 || e.keyCode == 32 ) {
    toggleConsoleFullscreen();
  }
});

function toggleConsoleFullscreen() {
  document.getElementById("console-wrapper").classList.toggle('fullscreen');
}
</script>

lib/webapp_web/templates/machine/my_machines.html.eex
<nav class="breadcrumb" aria-label="breadcrumbs">
  <ul>
    <li><%= link "Home", to: Routes.page_path(@conn, :index) %></li>
    <%= if @hypervisor do %>
      <li><%= link "Hypervisors", to: team_path(:admin_hypervisor_path, @conn, :index) %></li>
      <li><%= link @hypervisor.name, to: team_path(:admin_hypervisor_path, @conn, :show, @hypervisor)  %></li>
    <% end %>

    <li class="is-active"><a>Machines</a></li>
  </ul>
</nav>

<%= if @hypervisor do %>
  <%= render WebappWeb.HypervisorView, "_menu.html",  Map.put(assigns, :hide_status, false) %>
<% end %>

<div class="level">
  <div class="level-left">
    <h1>Listing Machines</h1>
  </div>

  <div class="level-right">
    <%= render WebappWeb.MachineView, "_new_button.html", assigns %>
  </div>
</div>

<table class="table container is-fullwidth">
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th>Distribution</th>
      <th>Hypervisor</th>
      <th>Plan</th>
      <th>Networks</th>
    </tr>
  </thead>
  <tbody>
<%= for machine <- @machines do %>
    <tr>
      <td><%= link machine.name, to: team_path(:machine_path, @conn, :show, machine) %></td>
      <td>
        <div class="tags has-addons">
          <span class="tag status status-icon <%= map_status_to_css(machine.last_status) %>" data-status="<%= map_status_to_css(machine.last_status) %>"><i class="<%= status_icon(machine.last_status) %>"></i></span>
          <span class="tag status <%= map_status_to_css(machine.last_status) %>" data-status="<%= map_status_to_css(machine.last_status) %>"><%= machine.last_status %></span>
        </div>
      </td>
      <td><%= machine.distribution.name %> <%= machine.distribution.version %></td>
      <td><%= link machine.hypervisor.name, to: Routes.admin_hypervisor_path(@conn, :show, machine.hypervisor) %></td>
      <td><%= link machine.plan.name, to: Routes.admin_plan_path(@conn, :show, machine.plan) %></td>

      <td><ul>
        <%= for network <- machine.networks do %>
           <li><%= link "#{network.name} (#{network.network})", to: Routes.admin_network_path(@conn, :show, network) %></li>
        <% end %>
      </ul></td>
    </tr>
<% end %>
<%= if Enum.empty?(@machines) do %>
    <tr><td colspan="3">Empty here, add a machine...</td></tr>
<% end %>
  </tbody>
</table>

lib/webapp_web/templates/machine/settings.html.eex
<nav class="breadcrumb" aria-label="breadcrumbs">
  <ul>
    <li><%= link "Home", to: Routes.page_path(@conn, :index) %></li>
    <li><%= link "My Machines", to: team_path(:machine_path, @conn, :index) %></li>
    <li><%= link @machine.name, to: team_path(:machine_path, @conn, :show, @machine)  %></li>
    <li class="is-active"><a>Settings</a></li>
  </ul>
</nav>

<%= render "_menu.html", assigns %>


  <%= if can?(@current_user, :new, Network) do %>
    <div class="settings-item">
      <div class="level">
        <div class="level-left">
          <h3>Connect machine to networks</h3>
        </div>
      </div>
      <%= render "settings/_networks.html", Map.put(assigns, :other_networks, @networks -- @machine.networks) %>
    </div>
    <div class="is-divider"></div>
  <% end %>

  <%= if machine_can_do?(@machine, :delete) do %>

    <div class="settings-item">
      <div class="level">
        <div class="level-left">
          <h3>Delete machine</h3>
        </div>

        <div class="level-right">
        </div>
      </div>

      <div class="box">
         <div class="notification is-danger">This operation cannot be reverted. Would you like to proceed?</div>
         <%= link "Delete", to: team_path(:machine_path, @conn, :delete, @machine), method: :delete, data: [confirm: "Are you sure?"], class: "button is-rounded is-danger"  %>
      </div>
    </div>
  <% end %>

lib/webapp_web/templates/machine/show.html.eex
<nav class="breadcrumb" aria-label="breadcrumbs">
  <ul>
    <li><%= link "Home", to: Routes.page_path(@conn, :index) %></li>
    <li><%= link "My Machines", to: team_path(:machine_path, @conn, :index) %></li>
    <li class="is-active"><a><%= @machine.name %></a></li>
  </ul>
</nav>

<%= render "_menu.html", assigns %>

<div class="box">
  <ul>
    <li>
      <strong>Name:</strong>
      <%= @machine.name %>
    </li>

    <%= for ip <- @machine.ipv4 do %>
    <li>
      <strong>IP:</strong>
      <%= ip.ip %>
      <strong>Gateway:</strong>
      <%= ip.ip_pool.gateway %>

      <strong>Netmask:</strong>
      <%= ip.ip_pool.netmask %>
    </li>
    <% end %>

    <li>
      <strong>Distribution:</strong>
      <%= if @machine.distribution do %>
      <%= @machine.distribution.name %> <%= @machine.distribution.version %>
      <% end %>
    </li>

    <li>
      <strong>Region:</strong>
      <%= @machine.hypervisor.region.name %>
    </li>

    <li>
      <strong>Plan:</strong>
      <%= @machine.plan.name %>
    </li>
  </ul>
</div>